<a href="https://colab.research.google.com/github/Adh101/TechAxis-Data-Science-with-Python-Notes/blob/main/Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to Numpy**

Numpy, short for Numerical Python, is a powerful Python library that enables efficient and convenient array manipulation and mathematical operations. It forms the foundation for many scientific and data-related tasks.

In [1]:
pip install numpy

**Importing numpy:**

In [2]:
import numpy as np

**Creating arrays:**

Arrays are the building blocks of Numpy, and they can be thought of as lists but with enhanced features.

You can create arrays filled with zeros, ones, or any constant using np.zeros(), np.ones(), and np.full():

In [ ]:
zero_arrays = np.zeros(10)
zero_arrays

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
ones_arrays = np.ones(10)
ones_arrays

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
full_arrays = np.full(10,3)
full_arrays

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

**Converting List to Arrays:**

To convert a Python list into a Numpy array, you can use np.array():

In [7]:
my_list = [1,2,3,4]
array_from_list = np.array(my_list)
array_from_list

array([1, 2, 3, 4])

In [8]:
#accessing the array values
array_from_list[0]

1

In [9]:
array_from_list[2]

3

In [10]:
#modifying the values
array_from_list[2] = 10
array_from_list

array([ 1,  2, 10,  4])

In [3]:
a =["ram","hari","shyam"]
array_a = np.array(a)
array_a

array(['ram', 'hari', 'shyam'], dtype='<U5')

In [5]:
a[2]=10
array_a

array(['ram', 'hari', 'shyam'], dtype='<U5')

In [11]:
array_from_list[3] = 'Shyam'

ValueError: ignored

**Generating ranges of numbers to create array:**



In [ ]:
range_array = np.arange(10) #create an array from 0 to 9
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3,15,2) #start,end, step

array([ 3,  5,  7,  9, 11, 13])

**Creating arrays with linear spacing:**

np.linspace() creates arrays with evenly spaced numbers within a specified range:

In [ ]:
np.linspace(0,1,11) #creates 11 numbers in aa

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
np.linspace(10,20,20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

# Multidimensional Array:
- It is also called matrices.
- We define rows and columns to create the matrices.

In [ ]:
zeros_matrix = np.zeros((5,2)) #np.zeros((rows,columns))
zeros_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
ones_matrix = np.ones((5,2)) #np.ones((rows,cols))
ones_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
constant_matrix = np.full((5,2),3) #np.full((rows,cols),value)
constant_matrix

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [ ]:
#lists to array
n = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#accessing the contents
n[0,1] #access 2

2

In [ ]:
n[2,1]

8

In [ ]:
n[1,1] = 20 #changes values 5 to 20
n

array([[ 1,  2,  3],
       [ 4, 20,  6],
       [ 7,  8,  9]])

In [ ]:
n[2] = [1,1,1] #changes the entire last row
n

array([[ 1,  2,  3],
       [ 4, 20,  6],
       [ 1,  1,  1]])

In [ ]:
n[:,2] = [1,1,1] #changes the entire last columns
n

array([[ 1,  2,  1],
       [ 4, 20,  1],
       [ 1,  1,  1]])

In [13]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
first_row = arr[0]      # Gets the first row
first_col = arr[:, 0]  # Gets the first column

**Randomly Generated Arrays:**

In [ ]:
np.random.rand(5,2) #creates random arrays everytime we run it

array([[0.9774341 , 0.86138595],
       [0.5423782 , 0.37730607],
       [0.04033074, 0.74916968],
       [0.84812808, 0.63962564],
       [0.84970436, 0.13805064]])

In [ ]:
#to create same array
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
# for arrays with normal distribution
np.random.seed(10)
np.random.randn(5,2)

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021]])

In [ ]:
#for arrays with integer values
np.random.seed(10)
np.random.randint(low = 0, high = 100, size=(5,2))

array([[ 9, 15],
       [64, 28],
       [89, 93],
       [29,  8],
       [73,  0]])

# Array Operations:

**1. Element wise Operations:**

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a = a + 10 #addition
a

array([10, 11, 12, 13, 14])

In [ ]:
a = a - 10 #subtraction
a

array([0, 1, 2, 3, 4])

In [ ]:
a = a * 5 #multiplication
a

array([ 0,  5, 10, 15, 20])

In [ ]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [ ]:
a+b #two arrays addition

array([ 0,  6, 12, 18, 24])

In [ ]:
arr1 = np.ones(4)
arr2 = np.full(4, 3)
result1 = arr1 + arr2  # Element-wise addition
result2 = arr1 / arr2  # Element-wise division

In [ ]:
result1

array([4., 4., 4., 4.])

In [ ]:
result2

array([0.33333333, 0.33333333, 0.33333333, 0.33333333])

2. **Comparision Operations:**

In [ ]:
a

array([ 0,  5, 10, 15, 20])

In [ ]:
a > 5

array([False, False,  True,  True,  True])

In [ ]:
a <= 10

array([ True,  True,  True, False, False])

In [ ]:
selected_elements = a[a<=10] #select the elements satisfying the condition
selected_elements

array([ 0,  5, 10])

**3. Summarizing Operations:**

In [ ]:
arr

array([[2, 3, 4],
       [4, 5, 6]])

In [ ]:
arr.min()

2

In [ ]:
arr.max()

6

In [ ]:
arr.mean()

4.0

In [ ]:
arr.std()

1.2909944487358056

In [ ]:
arr.sum()

24

In [ ]:
np.corrcoef(arr)

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.median(arr)

4.0

In [ ]:
np.append(a,b)

array([ 0,  5, 10, 15, 20,  0,  1,  2,  3,  4])

**Additional Resources:**
- [Numpy Cheatsheet](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

