<a href="https://colab.research.google.com/github/Adh101/TechAxis-Data-Science-with-Python-Notes/blob/main/Linear_Algebra_Refresher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra:

**Topics covered:**

- Vector Operations
- Multiplication
  
  - Vector-Vector
  - Matrix-Vector
  - Matrix-Matrix

- Identity Matrix
- Inverse


In [2]:
#import numpy
import numpy as np

**Vector Operations:**

In [3]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

# addition
addition = u + v

# subtraction
subtraction = u - v

# scalar multiplication
scalar_multiplication = 2 * v

**Multiplication:**

1. **Vector-Vector Multiplication (dot product):**

Vector: matrix with one dimension (one row matrix or one column matrix)

        result = summation of (u[i] * v[i]) from 1 to n (or, 0 to n-1)

In [4]:
#check the shape of vectors
u.shape
v.shape

(4,)

In [5]:
u.shape[0]

4

In [6]:
#fucntion for dot product

def vector_vector_multiplication(u,v):
  assert u.shape[0]==v.shape[0] #checks and asserts the shape of u and v

  n = u.shape[0] #sets the value for n to iterate

  result = 0.0   #sets the initial result value

  for i in range(n):
    result = result + u[i] * v[i]

  return result




In [7]:
vector_vector_multiplication(u,v)

110.0

In numpy, we already have function for dot product. i.e .dot()

In [8]:
u.dot(v)

110

   **2. Matrix-Vector Multiplication:**


        result = row of matrix * vector

In [9]:
U = np.array([
              [2,4,5,6],
              [1,2,1,2],
              [3,1,2,1]
])

In [ ]:
U.shape

(3, 4)

In [10]:
#function for matrix_vector multiplication

def matrix_vector_multiplication(U,v):
  assert U.shape[1] == v.shape[0] #asserting rows equals to columns

  num_rows = U.shape[0]
  result = np.zeros(num_rows) #create null matrix with number of rows of U

  for i in range(num_rows):
    result[i] = vector_vector_multiplication(U[i],v)

  return result

In [11]:
matrix_vector_multiplication(U,v)

array([98., 31., 35.])

In [ ]:
#we can also use dot function
U.dot(v)

array([98, 31, 35])

3. **Matrix-Matrix Multiplication:**

In [ ]:
V = np.array([
              [1,1,2],
              [0,0.5,1],
              [0,2,1],
              [2,1,0]
])

In [ ]:
def matrix_matrix_multiplication(U,V):
  assert U.shape[1] == V.shape[0]

  num_rows = U.shape[0]
  num_cols = V.shape[1]

  result = np.zeros((num_rows,num_cols))

  for i in range(num_cols):
    vi = V[:,i]
    Uvi = matrix_vector_multiplication(U,vi)

    result[:,i] = Uvi
  return result

In [ ]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [ ]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

**Identity Matrix:**

    U.I = U
    - All diagonal values should be 1 and other values 0.

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
I = np.eye(3)

In [ ]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

**Inverse matrix:**

In [ ]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [ ]:
#we need square matrix to get inverse
Vs= V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [ ]:
#inverse
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [ ]:
Vs_inv.dot(Vs) #gives identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])